AWSTemplateFormatVersion: "2010-09-09"

Resources:
  CentralNotificationBackupAlertRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: test-event-collector-forwarder-role
      Path: /
      PermissionsBoundary:
      Tags:

        - Key: "module_name"
          Value: "terraform-aws-acf-event-collector"
        - Key: "module_provider"
          Value: "ACAI GmbH"
        - Key: "module_source"
          Value: "github.com/acai-consulting/terraform-aws-acf-event-collector"
        - Key: "module_version"
          Value: "1.0.0"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "events.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: "backup_Alert_iam_policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: "sid"
                Effect: "Allow"
                Action:
                  - "events:PutEvents"
                Resource: arn:aws:events:eu-central-1:992382728088:event-bus/test
                
  CreateEventRulesfailed_aws_backups:
    Type: "AWS::Events::Rule"
    Properties:
      Name: failed_aws_backups
      Description:
      EventBusName: default
      EventPattern:
        source:
          - "aws.backup"
        detail-type:
          - "Backup Job State Change"
          - "Copy Job State Change"
        detail:
          state:
            - "FAILED"

      Targets:
        - Arn: arn:aws:events:eu-central-1:992382728088:event-bus/test
          Id: "SendToCentralEventBus"
          RoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/test-event-collector-forwarder-role
      Tags:
        - Key: "module_name"
          Value: "terraform-aws-acf-event-collector"
        - Key: "module_provider"
          Value: "ACAI GmbH"
        - Key: "module_source"
          Value: "github.com/acai-consulting/terraform-aws-acf-event-collector"
        - Key: "module_version"
          Value: "1.0.0"

  CreateEventRulesdisable_key_rotation:
    Type: "AWS::Events::Rule"
    Properties:
      Name: disable_key_rotation
      Description:
      EventBusName: default
      EventPattern:
        detail-type:
          - "AWS API Call via CloudTrail"
        detail:
          eventSource:
            - "kms.amazonaws.com"
          eventName:
            - "DisableKeyRotation"

      Targets:
        - Arn: arn:aws:events:eu-central-1:992382728088:event-bus/test
          Id: "SendToCentralEventBus"
          RoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/test-event-collector-forwarder-role
      Tags:
        - Key: "module_name"
          Value: "terraform-aws-acf-event-collector"
        - Key: "module_provider"
          Value: "ACAI GmbH"
        - Key: "module_source"
          Value: "github.com/acai-consulting/terraform-aws-acf-event-collector"
        - Key: "module_version"
          Value: "1.0.0"
